CREATE DATABASE STG_DB;
GRANT ALL PRIVILEGES ON DATABASE STG_DB TO user;

\c STG_DB;

CREATE TABLE feedback (
    id SERIAL PRIMARY KEY,
    image_name TEXT NOT NULL,
    predicted_result TEXT NOT NULL,
    user_feedback TEXT NOT NULL,
    is_good BOOLEAN NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);