name: Train Model

on:
  workflow_dispatch:  # Permet le déclenchement manuel
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le repo
        uses: actions/checkout@v4

      - name: Installer Python et dépendances
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installer les dépendances
        run: pip install -r requirements.txt

      - name: Entraîner le modèle
        run: python backend/train.py  # Script de réentraînement

      - name: Sauvegarder le modèle dans MLflow
        env:
          MLFLOW_TRACKING_URI: "http://mlflow:5000"
        run: |
          mlflow run . --experiment-name "fruit-classifier"

      - name: Commit du modèle mis à jour
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add models/
          git commit -m "🔄 Mise à jour du modèle entraîné"
          git push
